# Nesse desafio você colocará em prática o que aprendemos em relação a utilização do nginx como proxy reverso. 
# A idéia principal é que quando um usuário acesse o nginx, o mesmo fará uma chamada em nossa aplicação node.js. 
# Essa aplicação por sua vez adicionará um registro em nosso banco de dados mysql, cadastrando um nome na tabela **people**.
# O retorno da aplicação node.js para o nginx deverá ser:
# <h1>Full Cycle Rocks!</h1>
# - Lista de nomes cadastrada no banco de dados.
# Gere o docker-compose de uma forma que basta apenas rodarmos: 
# docker-compose up -d que tudo deverá estar funcionando e disponível na porta: 8080.
# Suba tudo em um repositório e faça a entrega.
# * A linguagem de programação para este desafio é Node/JavaScript.

version: '3'

services:
  nginx:
    build:
      context: nginx
    restart: always
    image: walopes/fullcyle_nginx
    container_name: nginx
    ports:
    - "8080:80"

  node:
    build:
      context: node
    image: walopes/fullcyle_node
    container_name: node
    restart: always
    tty: true
    # ports:
    # - "5000:5000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
